project_id = "rqdpedgodxocfrflbjow"

[functions.bootstrap]
verify_jwt = false

[functions.backup-database]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-get-users]
verify_jwt = false

[functions.admin-update-password]
verify_jwt = false
